//! Joining validated segments into one film (D-040, D-041).
//!
//! The concat demuxer plus a stream copy: no re-encode, no quality loss, and a
//! cost that is linear in file size rather than in pixels. That is only safe
//! because every segment was asserted against [`SegmentProfile`] before it got
//! here — measured in `ffmpeg-findings.md` §5, FFmpeg joins a mismatched
//! segment with **exit code 0 and no warning** (D-041), so the gate has to be
//! ours and it has to run before the join, not after.
//!
//! ## The list file is the one text format in this codebase
//!
//! Everything else reaches FFmpeg as an argument vector (D-011, D-052), where
//! a quote in a filename is data. The concat demuxer's list is different: it
//! is parsed as text, and `file 'a'b.mp4'` is a syntax error at best and a
//! different file at worst.
//!
//! Rather than escape our way out of that, this module refuses to write a name
//! it did not expect: segment filenames are generated by spoonstill, from a
//! scene index and a hash, and [`is_safe_list_name`] asserts that is what they
//! still are. An operator's own spelling never reaches this file — it reaches
//! the segment's *directory* and the film's *destination*, both of which are
//! argument vectors.

use std::path::{Path, PathBuf};
use std::time::Duration;

use spoonstill_core::diagnostics::{Diagnostics, Event};

use crate::atomic::{ensure_parent, move_into_place, partial_path};
use crate::command::FfmpegCommand;
use crate::error::MediaError;
use crate::probe::{self, DEFAULT_PROBE_TIMEOUT, ProbeResult};
use crate::profile::{self, SegmentProfile};
use crate::tools::Tools;

/// Ceiling for the join itself.
///
/// A stream copy of 500 segments is I/O, not encoding — minutes at worst on a
/// slow volume. An hour means something is wrong.
pub const CONCAT_TIMEOUT: Duration = Duration::from_secs(3_600);

/// How far the joined film's *video* may differ from the sum of its segments.
///
/// One frame. plan.md §M2 states the gate in exactly these terms: the film's
/// duration equals the sum of the resolved scene durations, within one frame.
#[must_use]
pub fn duration_tolerance(fps: u32) -> f64 {
    1.0 / f64::from(fps.max(1))
}

/// One AAC frame, in seconds.
///
/// The container's duration is the longest track's, and an AAC track carries
/// priming samples the video does not — measured here, a joined film's
/// container duration sits exactly 1024 samples (21.3 ms) above its video
/// duration, whether it holds two segments or six (`ffmpeg-findings.md` §10c).
/// So the container is allowed that much slack and the **video stream** is
/// what the frame-exactness gate is actually applied to.
pub const AAC_FRAME_SECONDS: f64 = 1024.0 / 48_000.0;

/// What the film must turn out to be.
#[derive(Debug, Clone, Copy)]
pub struct Expectation<'a> {
    /// The profile every segment already matched, which the film must too.
    pub profile: &'a SegmentProfile,
    /// Total frames, summed from the segments' asserted frame counts.
    pub frames: u64,
    /// Total duration, computed from those frames rather than measured.
    pub duration: f64,
    /// Frame rate, for the tolerance.
    pub fps: u32,
}

/// What the join produced.
#[derive(Debug, Clone)]
pub struct Film {
    /// Where the film now lives.
    pub path: PathBuf,
    /// Its measured duration.
    pub duration: f64,
    /// The sum of the segment durations it was built from.
    pub expected_duration: f64,
    /// The validating probe.
    pub probe: ProbeResult,
}

/// Whether a filename may appear in a concat list.
///
/// Deliberately narrow: ASCII letters, digits, `-`, `_` and `.`. This is not a
/// guess at what FFmpeg's parser accepts — it is the shape spoonstill's own
/// segment names have, and anything else means a name was built somewhere it
/// should not have been.
#[must_use]
pub fn is_safe_list_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with('.')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

/// Join validated segments into one film, and validate that too.
///
/// `expected_total` is the sum of the segment durations as *computed* from
/// frame counts, not as read back from the files — it is the number the film
/// is checked against.
///
/// # Errors
///
/// [`MediaError::UnusableInput`] when the segment list is empty, when the
/// segments do not share one directory, or when a filename is not one we
/// generated; [`MediaError::ProfileMismatch`] when the joined film does not
/// match the profile or drifts by more than a frame from `expected_total`;
/// and anything the process boundary reports.
pub fn concat(
    tools: &Tools,
    segments: &[PathBuf],
    dest: &Path,
    expect: &Expectation<'_>,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    let list = write_list(segments, dest)?;

    let result = run(tools, &list, dest, expect, log);

    // The list is scaffolding, not an artifact. It goes whether or not the
    // join worked — a leftover `.concat-*.txt` in a project folder is the kind
    // of litter that gets committed to somebody's repository.
    let _ = std::fs::remove_file(&list);
    result
}

fn run(
    tools: &Tools,
    list: &Path,
    dest: &Path,
    expect: &Expectation<'_>,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    ensure_parent(dest)?;
    let temporary = partial_path(dest);

    let mut command = FfmpegCommand::new(tools.ffmpeg());
    command
        .args(["-hide_banner", "-nostats", "-loglevel", "warning", "-y"])
        // `-safe 0` because the list holds relative names; the demuxer's safe
        // mode exists to stop a *downloaded* playlist from reaching arbitrary
        // paths, and this list was written four lines ago by us.
        .args(["-f", "concat", "-safe", "0"])
        .input(list)
        .args(["-c", "copy"])
        .arg(&temporary);

    let child = command.spawn()?;
    let display = child.display().to_string();
    log.record(&Event::info("ffmpeg", "running").with("command", display.clone()));

    let finished = match child.wait_until(CONCAT_TIMEOUT) {
        Ok(finished) => finished,
        Err(error) => {
            let _ = std::fs::remove_file(&temporary);
            return Err(error);
        }
    };

    if !finished.status.success() {
        log.record(
            &Event::error("ffmpeg", "concat exited non-zero")
                .with("command", display)
                .with("stderr", finished.stderr.clone()),
        );
        let _ = std::fs::remove_file(&temporary);
        finished.ok()?;
    }

    let film = match validate(tools, &temporary, expect, log) {
        Ok(film) => film,
        Err(error) => {
            let _ = std::fs::remove_file(&temporary);
            return Err(error);
        }
    };

    move_into_place(&temporary, dest)?;

    Ok(Film {
        path: dest.to_path_buf(),
        duration: film.duration,
        expected_duration: expect.duration,
        probe: film.probe,
    })
}

/// The D-041 gate, applied to the film rather than to a segment.
///
/// Frames are **not** counted by decoding here, and that is a considered
/// choice: decoding a 500-scene film to re-derive a number every segment
/// already asserted individually would cost minutes per run. What the film can
/// be wrong about that a segment cannot is its *contents as a list* — a
/// dropped, duplicated or reordered segment — and the three checks below catch
/// exactly that:
///
/// 1. the profile, because a stream copy can still produce a file whose header
///    disagrees with what went into it;
/// 2. the video stream's declared frame count, which for MP4 comes from the
///    sample table the copy just wrote and is off by a whole segment the
///    moment one goes missing;
/// 3. the video stream's duration, within one frame.
///
/// The **container's** duration is checked last and most loosely, because it
/// is the longest track's, and AAC priming makes the audio track outlast the
/// video by one AAC frame.
fn validate(
    tools: &Tools,
    path: &Path,
    expect: &Expectation<'_>,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    let probed = probe::probe(tools, path, DEFAULT_PROBE_TIMEOUT)?;

    if let Err(mismatches) = profile::assert_matches_profile(expect.profile, &probed) {
        for mismatch in &mismatches {
            log.record(
                &Event::error("profile", "film field does not match")
                    .with("path", path.display().to_string())
                    .with("field", mismatch.field)
                    .with("expected", mismatch.expected.clone())
                    .with("actual", mismatch.actual.clone()),
            );
        }
        return Err(MediaError::ProfileMismatch {
            path: path.to_path_buf(),
            mismatches,
        });
    }

    let video = probed.video().ok_or_else(|| MediaError::UnusableInput {
        path: path.to_path_buf(),
        detail: "the joined film has no video stream".into(),
    })?;

    let mut wrong: Vec<profile::Mismatch> = Vec::new();

    if let Some(declared) = video.nb_frames.filter(|d| *d != expect.frames) {
        wrong.push(profile::Mismatch {
            field: "nb_frames",
            expected: expect.frames.to_string(),
            actual: declared.to_string(),
        });
    }

    let tolerance = duration_tolerance(expect.fps);
    match video.duration.filter(|d| d.is_finite() && *d > 0.0) {
        Some(duration) if (duration - expect.duration).abs() <= tolerance => {}
        Some(duration) => wrong.push(profile::Mismatch {
            field: "video duration",
            expected: format!("{:.6} (+/- {tolerance:.6})", expect.duration),
            actual: format!("{duration:.6}"),
        }),
        None => wrong.push(profile::Mismatch {
            field: "video duration",
            expected: format!("{:.6}", expect.duration),
            actual: "<undeclared>".to_owned(),
        }),
    }

    let container = probed
        .format_duration
        .filter(|d| d.is_finite() && *d > 0.0)
        .ok_or_else(|| MediaError::UnusableInput {
            path: path.to_path_buf(),
            detail: "the joined film declares no usable duration".into(),
        })?;

    let container_tolerance = tolerance + AAC_FRAME_SECONDS;
    if (container - expect.duration).abs() > container_tolerance {
        wrong.push(profile::Mismatch {
            field: "duration",
            expected: format!("{:.6} (+/- {container_tolerance:.6})", expect.duration),
            actual: format!("{container:.6}"),
        });
    }

    if !wrong.is_empty() {
        for mismatch in &wrong {
            log.record(
                &Event::error(
                    "profile",
                    "film does not match the scenes it was built from",
                )
                .with("path", path.display().to_string())
                .with("field", mismatch.field)
                .with("expected", mismatch.expected.clone())
                .with("actual", mismatch.actual.clone()),
            );
        }
        return Err(MediaError::ProfileMismatch {
            path: path.to_path_buf(),
            mismatches: wrong,
        });
    }

    Ok(Film {
        path: path.to_path_buf(),
        duration: container,
        expected_duration: expect.duration,
        probe: probed,
    })
}

/// Write the concat list beside the segments, using bare filenames.
///
/// Beside them because the demuxer resolves relative entries against the
/// list's own directory, and bare filenames because that is the only form this
/// module is willing to write (see the module docs).
fn write_list(segments: &[PathBuf], dest: &Path) -> Result<PathBuf, MediaError> {
    let Some(first) = segments.first() else {
        return Err(MediaError::UnusableInput {
            path: dest.to_path_buf(),
            detail: "there are no segments to join".into(),
        });
    };

    let directory = first
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .ok_or_else(|| MediaError::UnusableInput {
            path: first.clone(),
            detail: "a segment must live in a directory the concat list can sit beside".into(),
        })?;

    let mut body = String::with_capacity(segments.len() * 32);
    for segment in segments {
        if segment.parent() != Some(directory) {
            return Err(MediaError::UnusableInput {
                path: segment.clone(),
                detail: format!(
                    "every segment must be in one directory for the join; expected {}",
                    directory.display()
                ),
            });
        }
        let name = segment
            .file_name()
            .and_then(|n| n.to_str())
            .filter(|n| is_safe_list_name(n))
            .ok_or_else(|| MediaError::UnusableInput {
                path: segment.clone(),
                detail: "is not a name spoonstill generates, and a concat list is parsed \
                         as text rather than passed as an argument (D-052)"
                    .into(),
            })?;
        body.push_str("file '");
        body.push_str(name);
        body.push_str("'\n");
    }

    let list = partial_path(&directory.join("concat.txt"));
    std::fs::write(&list, body).map_err(|source| MediaError::Io {
        doing: "writing the concat list",
        path: list.clone(),
        source,
    })?;
    Ok(list)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_segment_names_are_accepted() {
        assert!(is_safe_list_name("seg-0001-3f2a9c1d5e6b7a80.mp4"));
        assert!(is_safe_list_name("seg-0500-0000000000000000.mp4"));
    }

    /// The names this refuses are the whole reason it exists. Each of these
    /// would either break the parse or silently name a different file.
    #[test]
    fn a_name_that_could_change_the_parse_is_refused() {
        for hostile in [
            "it's a segment.mp4",
            "seg 0001.mp4",
            "seg\n0002.mp4",
            "../escape.mp4",
            "ünïcode.mp4",
            "seg\"0003\".mp4",
            "",
            ".hidden.mp4",
        ] {
            assert!(!is_safe_list_name(hostile), "{hostile:?} must be refused");
        }
    }

    #[test]
    fn an_empty_segment_list_is_refused() {
        let error = write_list(&[], Path::new("/out/film.mp4")).expect_err("nothing to join");
        assert!(error.to_string().contains("no segments"), "{error}");
    }

    /// Bare filenames only work if every segment really is in that one
    /// directory — otherwise the demuxer resolves a name against the wrong
    /// place, or silently finds nothing.
    #[test]
    fn segments_from_two_directories_are_refused() {
        let segments = vec![
            PathBuf::from("/a/seg-0001-aaaaaaaaaaaaaaaa.mp4"),
            PathBuf::from("/b/seg-0002-bbbbbbbbbbbbbbbb.mp4"),
        ];
        let error = write_list(&segments, Path::new("/out/film.mp4")).expect_err("two directories");
        assert!(error.to_string().contains("one directory"), "{error}");
    }

    #[test]
    fn one_frame_of_tolerance_is_one_frame() {
        assert!((duration_tolerance(30) - 1.0 / 30.0).abs() < f64::EPSILON);
        assert!((duration_tolerance(24) - 1.0 / 24.0).abs() < f64::EPSILON);
        // Never a division by zero, whatever a caller passes.
        assert!(duration_tolerance(0).is_finite());

        // The container gets one AAC frame of extra slack, and no more: at
        // 30 fps that is 33 ms of frame plus 21 ms of priming, which is still
        // far below the 2 s a single dropped scene would move it by.
        const { assert!(AAC_FRAME_SECONDS > 0.021 && AAC_FRAME_SECONDS < 0.022) };
    }

    /// The list really is written with bare names, beside the segments.
    #[test]
    fn the_list_holds_bare_names_beside_the_segments() {
        let dir = std::env::temp_dir().join(format!("spoonstill-concat-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let segments = vec![
            dir.join("seg-0001-aaaaaaaaaaaaaaaa.mp4"),
            dir.join("seg-0002-bbbbbbbbbbbbbbbb.mp4"),
        ];

        let list = write_list(&segments, &dir.join("film.mp4")).expect("written");
        assert_eq!(list.parent(), Some(dir.as_path()));

        let body = std::fs::read_to_string(&list).unwrap();
        assert_eq!(
            body,
            "file 'seg-0001-aaaaaaaaaaaaaaaa.mp4'\nfile 'seg-0002-bbbbbbbbbbbbbbbb.mp4'\n"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}
