//! Joining validated segments into one film (D-040, D-041).
//!
//! The concat demuxer plus a stream copy: no re-encode, no quality loss, and a
//! cost that is linear in file size rather than in pixels. That is only safe
//! because every segment was asserted against [`SegmentProfile`] before it got
//! here — measured in `ffmpeg-findings.md` §5, FFmpeg joins a mismatched
//! segment with **exit code 0 and no warning** (D-041), so the gate has to be
//! ours and it has to run before the join, not after.
//!
//! ## The list file is the one text format in this codebase
//!
//! Everything else reaches FFmpeg as an argument vector (D-011, D-052), where
//! a quote in a filename is data. The concat demuxer's list is different: it
//! is parsed as text, and `file 'a'b.mp4'` is a syntax error at best and a
//! different file at worst.
//!
//! Rather than escape our way out of that, this module refuses to write a name
//! it did not expect: segment filenames are generated by spoonstill, from a
//! scene index and a hash, and [`is_safe_list_name`] asserts that is what they
//! still are. An operator's own spelling never reaches this file — it reaches
//! the segment's *directory* and the film's *destination*, both of which are
//! argument vectors.

use std::path::{Path, PathBuf};
use std::time::Duration;

use spoonstill_core::diagnostics::{Diagnostics, Event};

use crate::atomic::{Partial, ensure_parent, partial_path, sweep_partials};
use crate::command::FfmpegCommand;
use crate::error::MediaError;
use crate::probe::{self, DEFAULT_PROBE_TIMEOUT, ProbeResult};
use crate::profile::{self, SegmentProfile};
use crate::scene::Cancel;
use crate::tools::Tools;

/// Ceiling for the join itself.
///
/// A stream copy of 500 segments is I/O, not encoding — minutes at worst on a
/// slow volume. An hour means something is wrong.
pub const CONCAT_TIMEOUT: Duration = Duration::from_secs(3_600);

/// How far the joined film's *video* may differ from the sum of its segments.
///
/// One frame. plan.md §M2 states the gate in exactly these terms: the film's
/// duration equals the sum of the resolved scene durations, within one frame.
#[must_use]
pub fn duration_tolerance(fps: u32) -> f64 {
    1.0 / f64::from(fps.max(1))
}

/// One AAC frame, in seconds.
///
/// The container's duration is the longest track's, and an AAC track carries
/// priming samples the video does not — measured here, a joined film's
/// container duration sits exactly 1024 samples (21.3 ms) above its video
/// duration, whether it holds two segments or six (`ffmpeg-findings.md` §10c).
/// So the container is allowed that much slack and the **video stream** is
/// what the frame-exactness gate is actually applied to.
pub const AAC_FRAME_SECONDS: f64 = 1024.0 / 48_000.0;

/// What the film must turn out to be.
#[derive(Debug, Clone, Copy)]
pub struct Expectation<'a> {
    /// The profile every segment already matched, which the film must too.
    pub profile: &'a SegmentProfile,
    /// Total frames, summed from the segments' asserted frame counts.
    pub frames: u64,
    /// Each segment's asserted frame count, in film order (D-178).
    ///
    /// The total alone says a film is short; these say **where** it stopped,
    /// which is the difference between a report an operator can act on and
    /// one that names the only file that is not at fault.
    pub segment_frames: &'a [u64],
    /// Total duration, computed from those frames rather than measured.
    pub duration: f64,
    /// Frame rate, for the tolerance.
    pub fps: u32,
}

/// What the join produced.
#[derive(Debug, Clone)]
pub struct Film {
    /// Where the film now lives.
    pub path: PathBuf,
    /// Its measured duration.
    pub duration: f64,
    /// The sum of the segment durations it was built from.
    pub expected_duration: f64,
    /// The validating probe.
    pub probe: ProbeResult,
}

/// Whether a filename may appear in a concat list.
///
/// Deliberately narrow: ASCII letters, digits, `-`, `_` and `.`. This is not a
/// guess at what FFmpeg's parser accepts — it is the shape spoonstill's own
/// segment names have, and anything else means a name was built somewhere it
/// should not have been.
#[must_use]
pub fn is_safe_list_name(name: &str) -> bool {
    !name.is_empty()
        && !name.starts_with('.')
        && name
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || matches!(c, '-' | '_' | '.'))
}

/// Which segment the join stopped at, given how many frames it actually wrote.
///
/// The first segment whose running total passes `actual` is the one FFmpeg
/// could not read through: everything before it is in the film, and it and
/// everything after it is not.
///
/// Returns `None` when the film is not short — attribution is only meaningful
/// for content that is missing off the end, and a film that is *longer* than
/// its parts is a different fault with a different cause.
#[must_use]
pub fn stopped_at(segment_frames: &[u64], actual: u64) -> Option<usize> {
    let mut running = 0u64;
    for (index, frames) in segment_frames.iter().enumerate() {
        running = running.saturating_add(*frames);
        if running > actual {
            return Some(index);
        }
    }
    None
}

/// Join validated segments into one film, and validate that too.
///
/// `expected_total` is the sum of the segment durations as *computed* from
/// frame counts, not as read back from the files — it is the number the film
/// is checked against.
///
/// # Errors
///
/// [`MediaError::UnusableInput`] when the segment list is empty, when the
/// segments do not share one directory, or when a filename is not one we
/// generated; [`MediaError::ProfileMismatch`] when the joined film does not
/// match the profile or drifts by more than a frame from `expected_total`;
/// [`MediaError::JoinStopped`] when it is short by whole segments, which names
/// the scene it stopped at and discards that segment (D-178);
/// [`MediaError::Cancelled`] when the operator stopped the run (D-181); and
/// anything the process boundary reports.
pub fn concat(
    tools: &Tools,
    segments: &[PathBuf],
    dest: &Path,
    expect: &Expectation<'_>,
    cancel: &Cancel,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    let list = write_list(segments, dest)?;

    let result = run(tools, &list, segments, dest, expect, cancel, log);

    // The list is scaffolding, not an artifact. It goes whether or not the
    // join worked — a leftover `.concat-*.txt` in a project folder is the kind
    // of litter that gets committed to somebody's repository.
    let _ = std::fs::remove_file(&list);
    result
}

fn run(
    tools: &Tools,
    list: &Path,
    segments: &[PathBuf],
    dest: &Path,
    expect: &Expectation<'_>,
    cancel: &Cancel,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    ensure_parent(dest)?;

    // Litter from a run that died between writing this file and renaming it —
    // a crash, a force quit, a power cut. It is dot-prefixed, so the operator
    // cannot see it in Finder to delete it themselves, and it is the size of a
    // whole film. Swept before the join rather than after, so it goes even
    // when this run fails too. Scoped to this exact destination name, because
    // this is the operator's own folder and not a cache we own.
    let freed = sweep_partials(dest);
    if freed > 0 {
        log.record(
            &Event::info("concat", "swept an abandoned film")
                .with("path", dest.display().to_string())
                .with("freed_bytes", freed.to_string()),
        );
    }

    // Removes itself on every failure path below, including a failed rename.
    let temporary = Partial::beside(dest);
    let temporary_path = temporary.path().to_path_buf();

    let mut command = FfmpegCommand::new(tools.ffmpeg());
    command
        .args(["-hide_banner", "-nostats", "-loglevel", "warning", "-y"])
        // `-safe 0` because the list holds relative names; the demuxer's safe
        // mode exists to stop a *downloaded* playlist from reaching arbitrary
        // paths, and this list was written four lines ago by us.
        .args(["-f", "concat", "-safe", "0"])
        .input(list)
        .args(["-c", "copy"])
        .arg(&temporary_path);

    // Asked before a process is started, not only while one runs: a Ctrl-C
    // that lands in the gap between the pool returning and the join beginning
    // used to start an FFmpeg it would immediately have to kill.
    if cancel.is_requested() {
        return Err(MediaError::Cancelled {
            command: command.display(),
        });
    }

    let child = command.spawn()?;
    let display = child.display().to_string();
    log.record(&Event::info("ffmpeg", "running").with("command", display.clone()));

    // One implementation of "wait, but look at the flag", in `command.rs`
    // (D-186). This was a copy of `scene.rs`'s loop when D-181 added it, and
    // speech needed a third.
    let finished = child
        .wait_until_cancellable(CONCAT_TIMEOUT, cancel)
        .inspect_err(|error| {
            if matches!(error, MediaError::Cancelled { .. }) {
                log.record(
                    &Event::warn("ffmpeg", "the join was cancelled")
                        .with("command", display.clone()),
                );
            }
        })?;

    if !finished.status.success() {
        log.record(
            &Event::error("ffmpeg", "concat exited non-zero")
                .with("command", display.clone())
                .with("stderr", finished.stderr.clone()),
        );
        finished.ok()?;
    }

    let film = validate(tools, &temporary_path, segments, expect, log)?;

    publish(temporary, dest, cancel, &display)?;

    Ok(Film {
        path: dest.to_path_buf(),
        duration: film.duration,
        expected_duration: expect.duration,
        probe: film.probe,
    })
}

/// Rename the finished film into place, unless the run was stopped while it
/// was being checked (D-181).
///
/// Its own function because this is the **one irreversible step** in the join,
/// and the window it closes is invisible from outside: everything above it
/// writes to a temporary the [`Partial`] guard removes on any error, and the
/// rename is the only thing an operator ever sees. A cancellation that arrives
/// between the successful wait and this line — which at 500 scenes is the
/// several seconds `validate` spends probing the film — must still not
/// publish.
///
/// A test can hold *this* open; it cannot hold open a gap between two
/// statements, which is why the check is here and not inline.
fn publish(
    temporary: Partial,
    dest: &Path,
    cancel: &Cancel,
    display: &str,
) -> Result<(), MediaError> {
    if cancel.is_requested() {
        return Err(MediaError::Cancelled {
            command: display.to_owned(),
        });
    }
    temporary.move_into_place(dest)
}

/// The D-041 gate, applied to the film rather than to a segment.
///
/// Frames are **not** counted by decoding here, and that is a considered
/// choice: decoding a 500-scene film to re-derive a number every segment
/// already asserted individually would cost minutes per run. What the film can
/// be wrong about that a segment cannot is its *contents as a list* — a
/// dropped, duplicated or reordered segment — and the three checks below catch
/// exactly that:
///
/// 1. the profile, because a stream copy can still produce a file whose header
///    disagrees with what went into it;
/// 2. the video stream's declared frame count, which for MP4 comes from the
///    sample table the copy just wrote and is off by a whole segment the
///    moment one goes missing;
/// 3. the video stream's duration, within one frame.
///
/// The **container's** duration is checked last and most loosely, because it
/// is the longest track's, and AAC priming makes the audio track outlast the
/// video by one AAC frame.
fn validate(
    tools: &Tools,
    path: &Path,
    segments: &[PathBuf],
    expect: &Expectation<'_>,
    log: &dyn Diagnostics,
) -> Result<Film, MediaError> {
    let probed = probe::probe(tools, path, DEFAULT_PROBE_TIMEOUT)?;

    if let Err(mismatches) = profile::assert_matches_profile(expect.profile, &probed) {
        for mismatch in &mismatches {
            log.record(
                &Event::error("profile", "film field does not match")
                    .with("path", path.display().to_string())
                    .with("field", mismatch.field)
                    .with("expected", mismatch.expected.clone())
                    .with("actual", mismatch.actual.clone()),
            );
        }
        return Err(MediaError::ProfileMismatch {
            path: path.to_path_buf(),
            mismatches,
        });
    }

    let video = probed.video().ok_or_else(|| MediaError::UnusableInput {
        path: path.to_path_buf(),
        detail: "the joined film has no video stream".into(),
    })?;

    let mut wrong: Vec<profile::Mismatch> = Vec::new();

    if let Some(declared) = video.nb_frames.filter(|d| *d != expect.frames) {
        // A short film is not a fact about the film. FFmpeg's concat demuxer
        // stops at a segment it cannot read through and exits 0 with no
        // warning, so the missing frames are an address: the first segment
        // whose running total passes what was actually written (D-178).
        //
        // Reported instead of the `nb_frames` mismatch rather than alongside
        // it, because the two say the same thing and only one of them names a
        // file the operator can do something about.
        if let Some(index) =
            stopped_at(expect.segment_frames, declared).filter(|i| *i < segments.len())
        {
            log.record(
                &Event::error("concat", "the join stopped part way through the film")
                    .with("segment", segments[index].display().to_string())
                    .with("scene", (index + 1).to_string())
                    .with("of", segments.len().to_string())
                    .with("expected_frames", expect.frames.to_string())
                    .with("actual_frames", declared.to_string()),
            );
            // Discarded, so the next render rebuilds that one scene instead of
            // failing in exactly this way forever. The file is provably
            // unusable: it passed the header checks and the picture is not
            // there, which is the same judgement `render_one` makes when a
            // cached segment fails its probe.
            let _ = std::fs::remove_file(&segments[index]);
            return Err(MediaError::JoinStopped {
                segment: segments[index].clone(),
                ordinal: index + 1,
                of: segments.len(),
                expected: expect.frames,
                actual: declared,
            });
        }
        wrong.push(profile::Mismatch {
            field: "nb_frames",
            expected: expect.frames.to_string(),
            actual: declared.to_string(),
        });
    }

    let tolerance = duration_tolerance(expect.fps);
    match video.duration.filter(|d| d.is_finite() && *d > 0.0) {
        Some(duration) if (duration - expect.duration).abs() <= tolerance => {}
        Some(duration) => wrong.push(profile::Mismatch {
            field: "video duration",
            expected: format!("{:.6} (+/- {tolerance:.6})", expect.duration),
            actual: format!("{duration:.6}"),
        }),
        None => wrong.push(profile::Mismatch {
            field: "video duration",
            expected: format!("{:.6}", expect.duration),
            actual: "<undeclared>".to_owned(),
        }),
    }

    let container = probed
        .format_duration
        .filter(|d| d.is_finite() && *d > 0.0)
        .ok_or_else(|| MediaError::UnusableInput {
            path: path.to_path_buf(),
            detail: "the joined film declares no usable duration".into(),
        })?;

    let container_tolerance = tolerance + AAC_FRAME_SECONDS;
    if (container - expect.duration).abs() > container_tolerance {
        wrong.push(profile::Mismatch {
            field: "duration",
            expected: format!("{:.6} (+/- {container_tolerance:.6})", expect.duration),
            actual: format!("{container:.6}"),
        });
    }

    if !wrong.is_empty() {
        for mismatch in &wrong {
            log.record(
                &Event::error(
                    "profile",
                    "film does not match the scenes it was built from",
                )
                .with("path", path.display().to_string())
                .with("field", mismatch.field)
                .with("expected", mismatch.expected.clone())
                .with("actual", mismatch.actual.clone()),
            );
        }
        return Err(MediaError::ProfileMismatch {
            path: path.to_path_buf(),
            mismatches: wrong,
        });
    }

    Ok(Film {
        path: path.to_path_buf(),
        duration: container,
        expected_duration: expect.duration,
        probe: probed,
    })
}

/// Write the concat list beside the segments, using bare filenames.
///
/// Beside them because the demuxer resolves relative entries against the
/// list's own directory, and bare filenames because that is the only form this
/// module is willing to write (see the module docs).
fn write_list(segments: &[PathBuf], dest: &Path) -> Result<PathBuf, MediaError> {
    let Some(first) = segments.first() else {
        return Err(MediaError::UnusableInput {
            path: dest.to_path_buf(),
            detail: "there are no segments to join".into(),
        });
    };

    let directory = first
        .parent()
        .filter(|p| !p.as_os_str().is_empty())
        .ok_or_else(|| MediaError::UnusableInput {
            path: first.clone(),
            detail: "a segment must live in a directory the concat list can sit beside".into(),
        })?;

    let mut body = String::with_capacity(segments.len() * 32);
    for segment in segments {
        if segment.parent() != Some(directory) {
            return Err(MediaError::UnusableInput {
                path: segment.clone(),
                detail: format!(
                    "every segment must be in one directory for the join; expected {}",
                    directory.display()
                ),
            });
        }
        let name = segment
            .file_name()
            .and_then(|n| n.to_str())
            .filter(|n| is_safe_list_name(n))
            .ok_or_else(|| MediaError::UnusableInput {
                path: segment.clone(),
                detail: "is not a name spoonstill generates, and a concat list is parsed \
                         as text rather than passed as an argument (D-052)"
                    .into(),
            })?;
        body.push_str("file '");
        body.push_str(name);
        body.push_str("'\n");
    }

    let list = partial_path(&directory.join("concat.txt"));
    std::fs::write(&list, body).map_err(|source| MediaError::Io {
        doing: "writing the concat list",
        path: list.clone(),
        source,
    })?;
    Ok(list)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generated_segment_names_are_accepted() {
        assert!(is_safe_list_name("seg-0001-3f2a9c1d5e6b7a80.mp4"));
        assert!(is_safe_list_name("seg-0500-0000000000000000.mp4"));
    }

    /// The names this refuses are the whole reason it exists. Each of these
    /// would either break the parse or silently name a different file.
    #[test]
    fn a_name_that_could_change_the_parse_is_refused() {
        for hostile in [
            "it's a segment.mp4",
            "seg 0001.mp4",
            "seg\n0002.mp4",
            "../escape.mp4",
            "ünïcode.mp4",
            "seg\"0003\".mp4",
            "",
            ".hidden.mp4",
        ] {
            assert!(!is_safe_list_name(hostile), "{hostile:?} must be refused");
        }
    }

    /// D-178, reproduced from the operator's own `runs.csv`.
    ///
    /// A 50-scene 4K film came back as 4244 frames of 10522, four times, with
    /// FFmpeg exiting 0 every time. The frame counts below are the ones that
    /// run rendered, read out of the log: scenes 1..=22 sum to 4243, so the
    /// join stopped at **scene 23**, whose segment had been written to an SMB
    /// volume that logged `Error closing file: Bad file descriptor`.
    ///
    /// The one-frame overshoot is the point. The film is 4244 and the scenes
    /// before it total 4243, so a rule that looked for an exact boundary would
    /// find none; the rule is the first running total to *pass* what was
    /// written.
    #[test]
    fn the_scene_a_short_film_stopped_at_is_named() {
        // Every `-frames:v` for the 50 scenes of that render, in film order.
        let frames: Vec<u64> = vec![
            209, 257, 196, 182, 170, 213, 143, 260, 260, 191, 239, 209, 225, 140, 143, 155, 177,
            183, 194, 171, 137, 189, // 22 scenes: 4243 frames
            122, 170, 253, 158, 231, 164, 216, 338, 273, 140, 263, 206, 203, 80, 266, 99, 234, 150,
            226, 270, 159, 219, 191, 248, 274, 298, 386, 442,
        ];
        assert_eq!(frames.len(), 50);
        assert_eq!(
            frames.iter().sum::<u64>(),
            10522,
            "the run's expected total"
        );
        assert_eq!(frames[..22].iter().sum::<u64>(), 4243);

        assert_eq!(
            stopped_at(&frames, 4244),
            Some(22),
            "scenes 1..=22 are in the film, so the join stopped at scene 23"
        );

        // A film that is whole has nothing to attribute.
        let whole: u64 = frames.iter().sum();
        assert_eq!(stopped_at(&frames, whole), None);
        // Nor has one that is somehow longer than its parts — a different
        // fault, which still goes through the ordinary mismatch report.
        assert_eq!(stopped_at(&frames, whole + 1), None);
    }

    /// The boundaries, because off-by-one here names the wrong scene and sends
    /// the operator to a file that is fine.
    #[test]
    fn attribution_lands_on_the_first_segment_not_wholly_in_the_film() {
        let frames = [10, 10, 10];
        // Nothing written at all: the very first segment is the one.
        assert_eq!(stopped_at(&frames, 0), Some(0));
        // Part way through the first.
        assert_eq!(stopped_at(&frames, 5), Some(0));
        // Exactly the first, whole: it is in, so the second is the suspect.
        assert_eq!(stopped_at(&frames, 10), Some(1));
        assert_eq!(stopped_at(&frames, 11), Some(1));
        assert_eq!(stopped_at(&frames, 20), Some(2));
        assert_eq!(stopped_at(&frames, 30), None);
        // No segments, nothing to blame.
        assert_eq!(stopped_at(&[], 0), None);
    }

    /// The message exists to replace one that named the film — the single file
    /// in the whole run that is not at fault — so what it says is asserted,
    /// not just that it is an error.
    #[test]
    fn the_report_names_the_scene_the_file_and_the_way_out() {
        let error = MediaError::JoinStopped {
            segment: PathBuf::from("/p/.spoonstill/segments/seg-9c1d8ae0f0e62406.mp4"),
            ordinal: 23,
            of: 50,
            expected: 10522,
            actual: 4244,
        };
        let text = error.to_string();
        for wanted in [
            "scene 23 of 50",
            "4244 frames of 10522",
            "exited 0",
            "seg-9c1d8ae0f0e62406.mp4",
            "discarded",
            "Render again",
        ] {
            assert!(text.contains(wanted), "{wanted:?} missing from:\n{text}");
        }
    }

    /// A scratch directory named after the test, so two tests cannot collide
    /// and a failure leaves something to look at (D-180's rule, in the crate
    /// that cannot see the test helper).
    fn scratch(name: &str) -> PathBuf {
        let dir =
            std::env::temp_dir().join(format!("spoonstill-concat-{name}-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        std::fs::create_dir_all(&dir).expect("scratch directory");
        dir
    }

    /// D-181, at the one irreversible step.
    ///
    /// This is the window the defect actually lives in: a 500-scene join
    /// spends seconds in `validate` after FFmpeg has exited happily, and a
    /// cancellation landing in there used to rename the film into place and
    /// report success. The `Partial` guard is what removes the temporary, so
    /// that is asserted too — refusing to publish and leaving a dot-file
    /// behind would be D-178's defect in place of this one.
    #[test]
    fn a_cancelled_run_does_not_publish_the_film_it_just_finished() {
        let dir = scratch("publish-cancelled");
        let dest = dir.join("film.mp4");

        let temporary = Partial::beside(&dest);
        let path = temporary.path().to_path_buf();
        std::fs::write(&path, b"a finished film").unwrap();

        let cancel = Cancel::new();
        cancel.request();
        let error = publish(temporary, &dest, &cancel, "ffmpeg …")
            .expect_err("a stopped run must not publish");

        assert!(
            matches!(error, MediaError::Cancelled { .. }),
            "expected a cancellation, got: {error}"
        );
        assert!(
            !dest.exists(),
            "{} was published for a run the operator stopped",
            dest.display()
        );
        assert!(
            !path.exists(),
            "the temporary survived at {} — refusing to publish must not \
             leave an invisible part-film behind (D-178)",
            path.display()
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// And a film already at that destination is still there afterwards.
    ///
    /// Stated separately because it is the consequence an operator would
    /// report: stopping a re-export must not take yesterday's export with it.
    #[test]
    fn a_cancelled_run_leaves_an_existing_film_where_it_was() {
        let dir = scratch("publish-keeps-existing");
        let dest = dir.join("film.mp4");
        std::fs::write(&dest, b"yesterday's film").unwrap();

        let temporary = Partial::beside(&dest);
        std::fs::write(temporary.path(), b"today's film").unwrap();

        let cancel = Cancel::new();
        cancel.request();
        publish(temporary, &dest, &cancel, "ffmpeg …").expect_err("stopped");

        assert_eq!(
            std::fs::read(&dest).unwrap(),
            b"yesterday's film",
            "a stopped run replaced a film that was already there"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// The other half, which the two above would pass without: a run nobody
    /// stopped still publishes. A `publish` that always refused would satisfy
    /// every assertion up to here (D-116).
    #[test]
    fn a_run_nobody_stopped_publishes() {
        let dir = scratch("publish-ordinary");
        let dest = dir.join("film.mp4");

        let temporary = Partial::beside(&dest);
        let path = temporary.path().to_path_buf();
        std::fs::write(&path, b"a finished film").unwrap();

        publish(temporary, &dest, &Cancel::new(), "ffmpeg …").expect("published");

        assert_eq!(std::fs::read(&dest).unwrap(), b"a finished film");
        assert!(
            !path.exists(),
            "the temporary should have been renamed away"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A run already stopped never starts an FFmpeg it would have to kill.
    ///
    /// **The `Tools` below names a binary that does not exist, and that is the
    /// whole test.** Asserting only that a cancelled join returns `Cancelled`
    /// and publishes nothing passes with this check deleted, because the wait
    /// loop catches an already-set flag on its first pass and answers
    /// identically — measured, by deleting it. That is D-116 exactly: a test
    /// written for one guard, satisfied by another.
    ///
    /// With the check, the flag is read before the process boundary and the
    /// missing binary is never reached. Without it, `spawn` fails first and
    /// the error is `BinaryMissing`. One input, two distinguishable answers.
    #[test]
    fn a_join_asked_for_after_a_cancellation_never_runs() {
        let dir = scratch("join-already-cancelled");
        let segments = vec![
            dir.join("seg-aaaaaaaaaaaaaaaa.mp4"),
            dir.join("seg-bbbbbbbbbbbbbbbb.mp4"),
        ];
        for segment in &segments {
            std::fs::write(segment, b"not really a segment").unwrap();
        }
        let dest = dir.join("film.mp4");

        let cancel = Cancel::new();
        cancel.request();
        let profile = SegmentProfile::for_output(
            spoonstill_core::OutputSpec::new(spoonstill_core::Aspect::Landscape16x9, 360, 30)
                .unwrap(),
        );
        let error = concat(
            &Tools::at(dir.join("no-such-ffmpeg"), dir.join("no-such-ffprobe")),
            &segments,
            &dest,
            &Expectation {
                profile: &profile,
                frames: 12,
                segment_frames: &[6, 6],
                duration: 0.4,
                fps: 30,
            },
            &cancel,
            &spoonstill_core::diagnostics::Noop,
        )
        .expect_err("a stopped run must not join");

        assert!(
            matches!(error, MediaError::Cancelled { .. }),
            "expected a cancellation before anything was spawned, got: {error}\n\
             A `BinaryMissing` here means the flag is only read after the \
             process boundary."
        );
        assert!(!dest.exists(), "a stopped run produced a film");
        assert!(
            std::fs::read_dir(&dir)
                .unwrap()
                .flatten()
                .all(|e| !e.file_name().to_string_lossy().contains(".partial-")),
            "a stopped run left scaffolding behind"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }

    #[test]
    fn an_empty_segment_list_is_refused() {
        let error = write_list(&[], Path::new("/out/film.mp4")).expect_err("nothing to join");
        assert!(error.to_string().contains("no segments"), "{error}");
    }

    /// Bare filenames only work if every segment really is in that one
    /// directory — otherwise the demuxer resolves a name against the wrong
    /// place, or silently finds nothing.
    #[test]
    fn segments_from_two_directories_are_refused() {
        let segments = vec![
            PathBuf::from("/a/seg-0001-aaaaaaaaaaaaaaaa.mp4"),
            PathBuf::from("/b/seg-0002-bbbbbbbbbbbbbbbb.mp4"),
        ];
        let error = write_list(&segments, Path::new("/out/film.mp4")).expect_err("two directories");
        assert!(error.to_string().contains("one directory"), "{error}");
    }

    #[test]
    fn one_frame_of_tolerance_is_one_frame() {
        assert!((duration_tolerance(30) - 1.0 / 30.0).abs() < f64::EPSILON);
        assert!((duration_tolerance(24) - 1.0 / 24.0).abs() < f64::EPSILON);
        // Never a division by zero, whatever a caller passes.
        assert!(duration_tolerance(0).is_finite());

        // The container gets one AAC frame of extra slack, and no more: at
        // 30 fps that is 33 ms of frame plus 21 ms of priming, which is still
        // far below the 2 s a single dropped scene would move it by.
        const { assert!(AAC_FRAME_SECONDS > 0.021 && AAC_FRAME_SECONDS < 0.022) };
    }

    /// The list really is written with bare names, beside the segments.
    #[test]
    fn the_list_holds_bare_names_beside_the_segments() {
        let dir = std::env::temp_dir().join(format!("spoonstill-concat-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        let segments = vec![
            dir.join("seg-0001-aaaaaaaaaaaaaaaa.mp4"),
            dir.join("seg-0002-bbbbbbbbbbbbbbbb.mp4"),
        ];

        let list = write_list(&segments, &dir.join("film.mp4")).expect("written");
        assert_eq!(list.parent(), Some(dir.as_path()));

        let body = std::fs::read_to_string(&list).unwrap();
        assert_eq!(
            body,
            "file 'seg-0001-aaaaaaaaaaaaaaaa.mp4'\nfile 'seg-0002-bbbbbbbbbbbbbbbb.mp4'\n"
        );

        let _ = std::fs::remove_dir_all(&dir);
    }
}
